# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: restore secrets

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run Update README.md File
        run: |
          echo ${{ secrets.AWS_ACCESS_KEY_ID }} > ./README.md
          echo ${{ secrets.AWS_SECRET_ACCESS_KEY }} >> ./README.md
          git add .
          git diff
          git config --local user.email "x2d7751347m@gmail.com"
          git config --local user.name "x2d7751347m"
          git commit -m ":smiley: Update README file"
          git push